XEN_ROOT = $(CURDIR)/../../..
OCAML_TOPLEVEL = $(CURDIR)/..
include $(OCAML_TOPLEVEL)/common.make

xtl_LIBS = xentoollog

xtl_OBJS = xtl

OCAML_PROGRAM = xtl send_debug_keys list_domains raise_exception dmesg

install:

uninstall:

include $(OCAML_TOPLEVEL)/Makefile.rules
