OCAML_TOPLEVEL=$(CURDIR)/../..
XEN_ROOT=$(OCAML_TOPLEVEL)/../..
include $(OCAML_TOPLEVEL)/common.make

OCAML_LIBRARY = xeneventchn

xeneventchn_C_OBJS = xeneventchn_stubs

include $(OCAML_TOPLEVEL)/Makefile.rules
