OCAML_TOPLEVEL=$(CURDIR)/../..
XEN_ROOT=$(OCAML_TOPLEVEL)/../..
include $(OCAML_TOPLEVEL)/common.make

OCAML_LIBRARY = xenmmap

xenmmap_C_OBJS = xenmmap_stubs

include $(OCAML_TOPLEVEL)/Makefile.rules
