ifdef V
	ifeq ("$(origin V)", "command line")
		BUILD_VERBOSE = $(V)
	endif
endif
ifndef BUILD_VERBOSE
	BUILD_VERBOSE := 0
endif
ifeq ($(BUILD_VERBOSE),1)
	E := @true
	Q :=
else
	E := @echo
	Q := @
endif

ALL_OCAML_OBJS ?= $(OBJS)

%.cmo: %.ml
	$(call quiet-command, $(OCAMLC) $(OCAMLCFLAGS) -c -o $@ $<,MLC,$@)

%.cmi: %.mli
	$(call quiet-command, $(OCAMLC) $(OCAMLCFLAGS) -c -o $@ $<,MLI,$@)

%.cmx %.o: %.ml
	$(call quiet-command, $(OCAMLOPT) $(OCAMLOPTFLAGS) -c -o $@ $<,MLOPT,$@)

%.ml: %.mll
	$(call quiet-command, $(OCAMLLEX) -q -o $@ $<,MLLEX,$@)

%.ml: %.mly
	$(call quiet-command, $(OCAMLYACC) -q $<,MLYACC,$@)

%.o: %.c
	$(call quiet-command, $(CC) $(CFLAGS) -c -o $@ $<,CC,$@)

distclean: clean

quiet-command = $(if $(V),$1,@printf " %-8s %s\n" "$2" "$3" && $1)
